### ISSUE TITLE
Add CONTRIBUTING guidelines

### ISSUE THREAD

**Issue by adrcav** [adrcav/cookies-notification#1]
Create a short guidelines called **CONTRIBUTING.md** for help people contribute to CookiesNotification repository.

**Comment by zikos2** [comment]
Can i start working on it

**Comment by crs2here** [comment]
HI I can pick this up. Does this repo just follow the systematic Git Workflow?

**Comment by adrcav** [comment]
Basically, yes.

The development mode starts using `npm start` command, and build is generated by `npm build`.
